name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun i && bun run build
      - uses: actions/upload-artifact@v4
        with:
          name: supercut-release
          path: dist/
          if-no-files-found: error
